#spring的配置
spring:
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.31.118.68:3306/bjsxt-his?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #                login-username: root
        #                login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#dubbo配置
dubbo:
  config-center:
    timeout: 10000 #显式声明连接zookeeper超时时间，默认3秒
  application:
    name: his-erp-service
  registry:
    address: zookeeper://113.31.118.68:2181
  protocol:
    name: dubbo
    port: 20881 # 这个端口需要指定一下，不然容易出现端口冲突
  consumer:
    check: false